// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace TradingCalendar
{
    public partial class BitcoinModel
    {
        /// <summary>
        /// model input class for BitcoinModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"SNo")]
            public float SNo { get; set; }

            [ColumnName(@"Name")]
            public string Name { get; set; }

            [ColumnName(@"Symbol")]
            public string Symbol { get; set; }

            [ColumnName(@"Date")]
            public string Date { get; set; }

            [ColumnName(@"High")]
            public float High { get; set; }

            [ColumnName(@"Low")]
            public float Low { get; set; }

            [ColumnName(@"Open")]
            public float Open { get; set; }

            [ColumnName(@"Close")]
            public float Close { get; set; }

            [ColumnName(@"Volume")]
            public float Volume { get; set; }

            [ColumnName(@"Marketcap")]
            public float Marketcap { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for BitcoinModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("BitcoinModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
