﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace TradingCalendar
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"Name", @"Name"),new InputOutputColumnPair(@"Symbol", @"Symbol")})      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"SNo", @"SNo"),new InputOutputColumnPair(@"High", @"High"),new InputOutputColumnPair(@"Low", @"Low"),new InputOutputColumnPair(@"Open", @"Open"),new InputOutputColumnPair(@"Volume", @"Volume"),new InputOutputColumnPair(@"Marketcap", @"Marketcap")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Date", @"Date"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Name",@"Symbol",@"SNo",@"High",@"Low",@"Open",@"Volume",@"Marketcap",@"Date"}))      
                                    .Append(mlContext.Regression.Trainers.FastForest(new FastForestRegressionTrainer.Options(){NumberOfTrees=563,FeatureFraction=0.531709358110212F,LabelColumnName=@"Close",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
